<?php

/**
* Implementation of hook_menu().
*/


function ajax_link_example_init(){
    drupal_add_js(drupal_get_path('module', 'ajax_link_example') . '/js/ajax_link_example.js', array('scope' => 'footer'));

}

function ajax_link_example_menu(){
    $items = array();

    $items['ajax-test'] = array(
        'title' => 'Ajax test',
        'type'  =>  MENU_NORMAL_ITEM,
        'access callback' => TRUE,
        'page callback' => 'ajax_link_example_page',
    );

    $items['ajax-test/%'] = array(
        'title' => 'Ajax test callback',
        'type' => MENU_CALLBACK,
        'page callback' => 'ajax_link_example_callback',
        'page arguments' => array(1),
        'access arguments' => array('access content'),
    );

    return $items;
}


function ajax_link_example_page(){
    return array(
        '#type' => 'link',
        '#title' => t('Ajax Link'),
        '#href' => 'ajax-test/nojs',
        '#prefix' => '<div id="ajax-link">',
        '#suffix' => '</div><div id="ajax-display"></div>',
        '#ajax' => array(
            'effect' => 'fade',
        ),
    );
}


function ajax_link_example_callback($ajax){
    $time = t('The current time is: !time', array('!time' => date('Y-m-d H:i:s')));
    //$time = 'test';
    error_log($time);

    if($ajax == 'ajax'){
        error_log($ajax);

        $commands = array();
        $commands[] = ajax_command_replace('#ajax-display',"<div id='ajax-display'>".$time."</div>");
        $commands[] = ajax_command_changed('#ajax-display');
        ajax_deliver(array('#type'=>'ajax','#commands' => $commands));
    }else{
        return array(
            '#markup' => $time
        );
    }
}


